# Generated by Django 5.0.6 on 2024-07-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsappApi',
        ),
        migrations.DeleteModel(
            name='WhatsappSession',
        ),
    ]
