# Generated by Django 5.0.6 on 2024-06-12 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.container', unique=True),
        ),
    ]
