# Generated by Django 5.0.6 on 2024-06-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.container'),
        ),
    ]
