# Generated by Django 5.0.6 on 2024-06-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='container',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.container'),
        ),
    ]
